### PR TITLE
New rax nodes

### PR DESCRIPTION
**Pull request by nigelbabu**
[Do not merge yet]

### CODE REVIEW

**Comment by mscherer** [comment]
Merged it, but the nodes do not have the ansible ssh keys.

**Comment by mscherer** [comment]
(oups, I just seen the message now :/ )

**Comment by mscherer** [comment]
I unmerged the merge, doing some magic server side.

**Comment by nigelbabu** [comment]
wait, why doesn't the nodes still have the ant-queen keys? Is that not part of the playbooks?

**Comment by mscherer** [comment]
Well, I can't connect to it to add the key. And the idea is that the key are added before the automation can kick in. We have nothing that add ant queen key there. I would also like to avoid duplicating the key between disk location and the playbook if possible.

**Pull request merged**
